apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx-proxy
  name: nginx-proxy
  namespace: lab
spec:
  ports:
  - name: 80-80
    nodePort: 32004
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-proxy
  type: NodePort
status:
  loadBalancer: {}
