apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy
  namespace: lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-proxy
  template:
    metadata:
      labels:
        app: nginx-proxy
    spec:
      containers:
      - name: nginx-proxy
        image: nginx
        resources: {}
        volumeMounts:
            - name: nginx-proxy-volume
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: nginx-proxy-volume
          configMap:
            name: nginx-proxy-config