apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: webapp
  name: webapp
spec:
  ports:
  - name: 80-80
    nodePort: 32002
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: webapp
  type: NodePort
status:
  loadBalancer: {}
