version: "3.9"
services:
  frontend:
    build: .
  nginx:
    build: ./nginx
    restart: always
    ports:
      - "3000:80"
    volumes:
      - /Users/er_macbook_228/devops-techmaster/containerization-2/tictac/public:/var/www/html
      - nginxdata:/var/www/public_nginx
    depends_on:
      - frontend
volumes:
  nginxdata: